# -*- coding: utf-8 -*-
"""AnaliseDados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YHzLKzgCjjiMLE1lwE2HaNJSi7NOJTy-
"""

pip install plotly

import pandas as pd
import plotly.express as px

tabela = pd.read_csv("cancelamentos.csv")
tabela = tabela.drop("CustomerID", axis=1)
display(tabela)

# info -> exibe valores não nulos
print(tabela.info())

# df.isna().any -> informa se há algum valor vazio
print(tabela.isna().any())

# df.isna().sum -> soma a  quantidade de valores vazios
print(tabela.isna().sum())

# Elimina valores vazios

tabela = tabela.dropna()
print(tabela.info())
display(tabela)

# Verificar quantas pessoas cancelaram

display(tabela["cancelou"].value_counts())


# Verificar percentual de pessoas que cancelaram

display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# Verificar cancelamento por tipo (prazo) de contrato

display(tabela["duracao_contrato"].value_counts(normalize=True))
display(tabela["duracao_contrato"].value_counts())

# verificar duração total do contrato por tipo (prazo)
# é possível observar que quase todos os contratos de prazo mensal cancelaram

display(tabela.groupby("duracao_contrato").mean(numeric_only=True))

# verificar apenas o contrato mensal

tabela = tabela[tabela["duracao_contrato"]!="Monthly"]
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# verificar apenas o contrato anual

tabela = tabela[tabela["duracao_contrato"]!="Annual"]
display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

# verificar por tipo de assinatura

display(tabela["assinatura"].value_counts())
#display(tabela["assinatura"].mean(numeric_only=True))

display(tabela["assinatura"].value_counts(normalize=True).map("{:.1%}".format))

# criar gráfico para visualizar

for coluna in tabela.columns:
    grafico = px.histogram(tabela, x=coluna, color="cancelou")
    grafico.show()

# os gráficos permitem observar que há 100% de cancelamento quando há:
#          atraso em mais de 20 dias ou mais de 5 ligações para call center

tabela = tabela[tabela["ligacoes_callcenter"]<5]
tabela = tabela[tabela["dias_atraso"]<=20]

display(tabela)

display(tabela["cancelou"].value_counts())
display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format))

